name: Tycoon
softdepend: [HolographicDisplays]
author: HeyAwesomePeople
main: me.HeyAwesomePeople.Tycoon.Tycoon
version: 1.0
commands:
  atycoon:
    aliases: [atyc, admintycoon, at]
    description: Admin command for Tycoon plugin
  tycoon:
    aliases: [tyc]
    description: Player command for Tycoon plugin